# Generated by Django 4.1.7 on 2024-11-20 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_alter_article_category_alter_article_main_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Стаття', 'verbose_name_plural': 'Статті'},
        ),
    ]
